# Generated by Django 6.0.6 on 2026-06-29 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], max_length=50)),
                ('fullname', models.CharField(max_length=100)),
                ('identity_code', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=11)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('', '----------'), ('Dentistry', 'Dentistry'), ('Pharmacy', 'Pharmacy'), ('Consultation', 'Consultation'), ('Flu Treatment', 'Flu Treatment'), ('ENT', 'Ear, Nose, and Throat (ENT)'), ('Reproductive Health', 'Reproductive Health'), ('Mental Health', 'Mental Health'), ('Physiotherapy', 'Physiotherapy'), ('Covid-Screening', 'Covid-19 Screening'), ('VCT', 'HIV Counselling & Treatment'), ('Laboratory', 'Laboratory Tests'), ('Referral', 'Referral'), ('Other issue', 'Other issue')], max_length=60)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='media/image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='account.user')),
            ],
        ),
    ]
