# Generated by Django 6.0.6 on 2026-07-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Dentistry', 'Dentistry'), ('Pharmacy', 'Pharmacy'), ('Consultation', 'Consultation'), ('Flu Treatment', 'Flu Treatment'), ('ENT', 'Ear, Nose, and Throat (ENT)'), ('Reproductive Health', 'Reproductive Health'), ('Mental Health', 'Mental Health'), ('Physiotherapy', 'Physiotherapy'), ('Covid-Screening', 'Covid-19 Screening'), ('VCT', 'HIV Counselling & Treatment'), ('Laboratory', 'Laboratory Tests'), ('Referral', 'Referral'), ('Other issue', 'Other issue')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
