# Generated by Django 6.0.6 on 2026-07-05 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_patient_image_alter_doctor_bio_alter_doctor_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
