# Generated by Django 6.0.6 on 2026-07-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('token', models.CharField(max_length=200, unique=True)),
                ('code', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.IntegerField(default=0)),
                ('failed', models.BooleanField(default=True)),
            ],
        ),
    ]
