# Generated by Django 6.0.6 on 2026-07-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='identity_code',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='otp',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
