# Generated by Django 6.0.6 on 2026-07-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
