# Generated by Django 6.0.6 on 2026-07-05 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_image'),
        ('appointment', '0002_rename_create_at_service_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='doctor',
        ),
        migrations.AddField(
            model_name='service',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='account.doctor'),
        ),
    ]
