# Generated by Django 6.0.6 on 2026-07-05 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_image'),
        ('appointment', '0003_remove_service_doctor_service_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='account.doctor'),
        ),
    ]
