# Generated by Django 6.0.6 on 2026-07-05 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_service_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinghour',
            name='slot_gap_time',
        ),
    ]
