# Generated by Django 6.0.6 on 2026-07-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_image'),
        ('appointment', '0005_remove_workinghour_slot_gap_time'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workinghour',
            constraint=models.UniqueConstraint(fields=('doctor', 'days_of_week'), name='unique working hour per day'),
        ),
    ]
