# Generated by Django 6.0.6 on 2026-07-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_workinghour_unique_working_hour_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghour',
            name='days_of_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='_Days of week'),
        ),
    ]
