# Generated by Django 6.0.6 on 2026-07-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_alter_workinghour_days_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='down_payment',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_to_pay',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
