# Generated by Django 6.0.6 on 2026-07-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_payment_down_payment_alter_payment_amount_to_pay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='appoinment',
            new_name='appointment',
        ),
    ]
