# Generated by Django 6.0.6 on 2026-07-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_rename_appoinment_payment_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
