# Generated by Django 6.0.6 on 2026-07-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_payment_remaining_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workinghour',
            old_name='days_of_week',
            new_name='day_of_week',
        ),
    ]
