# Generated by Django 6.0.6 on 2026-07-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_rename_days_of_week_workinghour_day_of_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workinghour',
            old_name='day_of_week',
            new_name='days_of_week',
        ),
    ]
