# Generated by Django 6.0.6 on 2026-07-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_rename_day_of_week_workinghour_days_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Authority',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
