# Generated by Django 6.0.6 on 2026-07-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_payment_authority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Authority',
            new_name='authority',
        ),
    ]
