# Generated by Django 6.0.6 on 2026-08-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0015_payment_created_at_payment_paid_at_payment_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cart_num',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
