# Generated by Django 6.0.6 on 2026-08-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0016_payment_cart_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='cart_num',
            new_name='card_num',
        ),
    ]
