# Generated by Django 6.0.6 on 2026-08-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0017_rename_cart_num_payment_card_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_num',
            field=models.CharField(blank=True, null=True),
        ),
    ]
